name: Flutter SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Evita shallow clones para melhor análise

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: Instalar Dependências
        run: flutter pub get

      - name: Executar Análise Estática do Flutter
        run: flutter analyze

      - name: Compilar Projeto para Android
        run: flutter build apk --debug

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=xXD4rkSoulXx_TaskSync \
            -Dsonar.organization=xxd4rksoulxx \
            -Dsonar.sources=lib \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
